#!/bin/sh
#
# @name Gazebo DMR60
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=dmr60_mocap}
. ${R}etc/init.d-posix/airframes/4101_gz_dmr60

param set-default EKF2_GPS_CTRL 0
param set-default EKF2_EV_CTRL 11
param set-default EKF2_HGT_REF 3


